name: ts 
version: '0.1' 
summary: test to run a python script
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel 
confinement: devmode 

parts:
  tc:
   source: ../tc
   plugin: dump 

#hooks:
#  install:
#    plugs: [network] 
# config-variable:
#     plugin: dump
#     source: config 
#  hello:
#    source: hello
#    plugin: python
#    python-version: python2

apps:
  ts1:
   command: ts1.sh
#  abc:
#   command: ab.sh
#  hello:
#   command: bin/pyt.py
